version: '3.1'

services:
  app:
    build:
      context: docker/local
      dockerfile: app.docker
    volumes:
      - ./:/var/www/html
      - ./docker/local/apache2log/:/var/log/apache2
    ports:
      - "80:80"
    links:
      - mailhog

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"
